import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <> 
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={`${styles.main} ${inter.className}`}>

        <h1 className={styles.title}>
          &lt;Cyber Scoop/&gt;
        </h1>

        <Image className={styles.myimg} alt = "Home image" src="/home.jpg" width={540} height={395} priority></Image>

        <p className={styles.description} style={{textAlign:"center"}}>
          A blog for scoopers looking to scoop code and share insights into the latest trends in technology, programming, and software development. This platform serves as a hub for enthusiasts and professionals alike to exchange knowledge, discuss new ideas, and foster a community of like-minded individuals passionate about coding and tech innovation.
        </p>

        <div className="blogs">
        <h2 style={{textAlign:"center"}}>Latest Blogs</h2>
          <div className="blogItem">
            <h3>Understanding Python Data Structures</h3>
            <p className={styles.description}>Python is a versatile programming language widely used for various applications. </p>
          </div>
          <div className="blogItem">
            <h3>A Deep Dive into Rust for Systems Programming</h3>
            <p className={styles.description}>Rust is a systems programming language designed for safety, speed, and concurrency.</p>
          </div>
          <div className="blogItem">
            <h3>Mastering SQL Queries for Data Analysis</h3>
            <p className={styles.description}>SQL, or Structured Query Language, is the standard language for managing databases.</p>
          </div>
        </div>
      </main>
    </>
  );
}
