import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <> 
    <style jsx>
      {`h2{
        font-size:38px;
      }
      h3{
        font-size:22px;
      }
      `}
    </style>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={`${styles.main} ${inter.className}`}>

        <h1 className={styles.title}>
          Cyber Scoop
        </h1>

        <Image className={styles.myimg} alt = "Home image" src="/home.jpg" width={640} height={427}></Image>

        <p className={styles.description} style={{justifyContent:"center"}}>
          A blog for scoopers looking to scoop code.
        </p>

        <div className="blogs">
        <h2>Latest Blogs</h2>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2022?</h3>
            <p className={styles.description}>Javascipt is the language is used to design logic for the web</p>
          </div>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2022?</h3>
            <p className={styles.description}>Javascipt is the language is used to design logic for the web</p>
          </div>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2022?</h3>
            <p className={styles.description}>Javascipt is the language is used to design logic for the web</p>
          </div>
        </div>
      </main>
    </>
  );
}
